version: '3.9'
services:
  python:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        - IMAGE_TAG=debian:latest
    image: skrjtech/scraping:amd64-debian-python3.9.16
    container_name: python
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw