version: '3.9'
services:
  test:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: skrjtech/yolact:amd64-10.0-cudnn7-devel-ubuntu18.04-python3.7.16
    container_name: yolact_test
    hostname: yolact
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/ws
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]