version: '3.9'
services:
  test:
    image: skrjtech/yolact:latest
    container_name: yolact_test
    hostname: yolact
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/ws
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]