version: '3.9'
services:
  mkuser:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        - IMAGE_TAG
        - USERNAME=$USER
        - GROUPNAME=$USER
        - PASSWORD=$USER
        - UID=1000
        - GID=1000
    image: $IMAGE_NAME
    